import type { Metadata } from "next";
import { Montserrat } from "next/font/google"
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const montserrat = Montserrat({ subsets: ["latin"] })



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en" className="scroll-smooth">
      <body className={ montserrat.className} >

        <Navbar></Navbar>

        <main>{children}</main>

        <Footer></Footer>

      </body>
    </html>
  );
}
